# Generated by Django 4.1.2 on 2022-10-11 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='description',
            field=models.CharField(blank=True, max_length=225),
        ),
    ]
